tests: Fix build due to missing STREQ
'make check' has been broken since commit 631851d:

  CC       cutest.o
cutest.c: In function 'CuAssertStrEquals_LineMsg':
cutest.c:121:10: warning: implicit declaration of function 'STREQ' [-Wimplicit-function-declaration]
          STREQ(expected, actual)))
          ^~~~~
cutest.c:121:10: warning: nested extern declaration of 'STREQ' [-Wnested-externs]

Signed-off-by: Eric Blake <eblake@redhat.com>