linux: include <bond> element for bonds with no slaves
The missing element makes libvirt sad:

  $ ncftool dumpxml --live nm-bond
  <?xml version="1.0"?>
  <interface name="nm-bond" type="bond">
    <link state="unknown" speed="0"/>
    <protocol family="ipv4">
      <ip address="1.2.3.4" prefix="8"/>
    </protocol>
  </interface>

  $ virsh iface-dumpxml nm-bond
  error: XML error: bond interface misses the bond element

This is analogous what was done in d32a464c (Always add <bridge> element to
bridge if, even if no physdev is attached) for bridges.